version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    # If you need environment variables, uncomment and add them below
    # environment:
    #   - REACT_APP_API_URL=http://your-api-url
    volumes:
      # For development hot-reloading (comment out in production)
      # - ./src:/app/src
      # Mount custom nginx config if needed
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    # Add healthcheck
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
