# Generated by Django 4.2.23 on 2025-09-08 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CROReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('ga4_report', models.TextField(blank=True, help_text='Google Analytics report', null=True)),
                ('hotjar_report', models.TextField(blank=True, help_text='Hotjar analysis report', null=True)),
                ('shopify_report', models.TextField(blank=True, help_text='Shopify data report', null=True)),
                ('comprehensive_report', models.TextField(blank=True, help_text='Combined CRO audit report', null=True)),
                ('uploaded_files_info', models.JSONField(default=dict, help_text='Information about uploaded CSV files')),
                ('api_provider', models.CharField(default='openai/gpt-4', max_length=100)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cro_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CRO Report',
                'verbose_name_plural': 'CRO Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
