# Generated by Django 4.2.23 on 2025-09-11 11:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('RAG', 'Retrieval Augmented Generation'), ('MEMO', 'Memory-Based Generation')], default='RAG', help_text='Type of AI agent to use for analysis', max_length=10)),
                ('ai_provider', models.CharField(choices=[('OpenAI', 'OpenAI'), ('Google Gemini', 'Google Gemini')], default='OpenAI', help_text='AI service provider for generating reports', max_length=20)),
                ('ai_model', models.CharField(choices=[('openai/gpt-4', 'OpenAI GPT-4'), ('openai/gpt-3.5-turbo', 'OpenAI GPT-3.5 Turbo'), ('gemini/gemini-pro', 'Google Gemini Pro'), ('gemini/gemini-1.5-pro', 'Google Gemini 1.5 Pro')], default='openai/gpt-4', help_text='Specific AI model to use for generating reports', max_length=50)),
                ('temperature', models.FloatField(default=0.7, help_text='Creativity/randomness of AI output (0.0-1.0)', validators=[django.core.validators.RegexValidator(message='Temperature must be between 0.0 and 1.0', regex='^(0(\\.\\d+)?|1(\\.0)?)$')])),
                ('max_tokens', models.PositiveIntegerField(default=4096, help_text='Maximum number of tokens for AI response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User whose settings these are', on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User AI Settings',
                'verbose_name_plural': 'User AI Settings',
            },
        ),
    ]
