# Generated by Django 4.2.23 on 2025-09-18 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='enable_dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture (max 5MB, jpg/png/gif)', null=True, upload_to='profile_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='receive_email_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_online_status',
            field=models.BooleanField(default=False),
        ),
    ]
