# Generated by Django 4.2.23 on 2025-09-22 10:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={},
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='enable_dark_mode',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='receive_email_updates',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='show_online_status',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile picture (max 5MB, jpg/png/gif)', null=True, upload_to='profile_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('receive_email_updates', models.BooleanField(default=True)),
                ('show_online_status', models.BooleanField(default=False)),
                ('enable_dark_mode', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User AI Settings',
                'verbose_name_plural': 'User AI Settings',
            },
        ),
    ]
