# Generated by Django 4.2.23 on 2025-09-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usersettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='refresh_token',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
