# Generated by Django 4.2.23 on 2025-09-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usertoken_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='google_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='openai_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
