# Generated by Django 4.2.23 on 2025-09-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_usersettings_google_key_usersettings_openai_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='croreport',
            name='report_name',
            field=models.CharField(blank=True, help_text='A name for the report', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='ai_model',
            field=models.CharField(choices=[('openai/gpt-4', 'OpenAI GPT-4'), ('openai/gpt-3.5-turbo', 'OpenAI GPT-3.5 Turbo'), ('gemini/gemini-pro', 'Google Gemini Pro'), ('gemini/gemini-1.5-pro', 'Google Gemini 1.5 Pro'), ('gemini-2.0-flash', 'Google Gemini 2.0 Flash')], default='openai/gpt-4', help_text='Specific AI model to use for generating reports', max_length=50),
        ),
    ]
