# Generated by Django 4.2.23 on 2025-09-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_croreport_report_name_alter_usersettings_ai_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croreport',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('inactive', 'Inactive')], default='processing', max_length=20),
        ),
    ]
