# Generated by Django 4.2.23 on 2025-09-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_croreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='company_name',
            field=models.CharField(blank=True, help_text='User company name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='job_title',
            field=models.CharField(blank=True, help_text='User job title', max_length=100, null=True),
        ),
    ]
