# Generated by Django 4.2.23 on 2025-09-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_job_title_company_to_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='enable_dark_mode',
            field=models.BooleanField(default=False, help_text='Whether user prefers dark mode UI'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='receive_email_updates',
            field=models.BooleanField(default=True, help_text='Whether the user wants to receive email updates'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_online_status',
            field=models.BooleanField(default=False, help_text='Whether to show user online status'),
        ),
    ]
