# Generated by Django 4.2.23 on 2025-09-25 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_account_preferences_to_usersettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'User AI Settings', 'verbose_name_plural': 'User AI Settings'},
        ),
        migrations.AlterModelOptions(
            name='usertoken',
            options={},
        ),
        migrations.RemoveField(
            model_name='usertoken',
            name='enable_dark_mode',
        ),
        migrations.RemoveField(
            model_name='usertoken',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='usertoken',
            name='receive_email_updates',
        ),
        migrations.RemoveField(
            model_name='usertoken',
            name='show_online_status',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture (max 5MB, jpg/png/gif)', null=True, upload_to='profile_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
